# Generated by Django 5.0.6 on 2024-08-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_is_company_user_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
    ]
