# Generated by Django 5.0.6 on 2024-08-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_organization_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
