# Generated by Django 5.0.6 on 2024-08-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_application_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
    ]
